apiVersion: v1
kind: Service
metadata:
  name: mediawiki
  labels:
    app: mediawiki
spec:
  ports:
    - port: 80
  selector:
    app: mediawiki
    tier: frontend
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki
  labels:
    app: mediawiki
spec:
  selector:
    matchLabels:
      app: mediawiki
      tier: frontend
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mediawiki
        tier: frontend
    spec:
      containers:
      - image: mohitkumarsharma/assignment
        name: mediawiki
        ports:
        - containerPort: 80
          name: mediawiki
