apiVersion: v1
kind: Service
metadata:
  name: mediawiki-mysql
  labels:
    app: mediawiki
spec:
  ports:
    - port: 3306
  selector:
    app: mediawiki
    tier: mysql
  clusterIP: None
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mediawiki-mysql
  labels:
    app: mediawiki
spec:
  selector:
    matchLabels:
      app: mediawiki
      tier: mysql
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mediawiki
        tier: mysql
    spec:
      containers:
      - image: mysql
        name: mysql
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-root-password
              key: rootpassword
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-database-name
              key: dbname
        - name: MYSQL_USER
          valueFrom:
            secretKeyRef:
              name: mysql-username
              key: username
        - name: MYSQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-pass
              key: password
        ports:
        - containerPort: 3306
          name: mysql
